### ISSUE TITLE
Linking to fmt static lib warns about -fPIC not set when fPIC option set to True

### ISSUE THREAD

**Issue by Manu343726** [memsharded/conan-fmt#2]
I'm trying to link fmt against a shared library of mine, and I had to switch to the dynamic fmt lib version (`shared=True`) because the static one cannot be linked against my dynamic lib, even if `fPIC` option is set to `True` in my conanfile.txt file.

I've checked your conanfile.py file and it seems you're handling the option correctly, so I should be doing something wrong. My use case is as follows:

 - **Require fmt:**
    ``` txt
    [requires]
    fmt/3.0.0@memsharded/testing
    [options]
    fmt:shared=False
    fmt:fPIC=True
    ```

 - **Import fmt-conan lib into my CMake project**:
     ``` cmake
     include(conanbuildinfo.cmake)
     conan_basic_setup()
     add_library(fmt-conan INTERFACE)
     target_include_directories(fmt-conan INTERFACE ${CONAN_INCLUDE_DIRS_FMT})

     find_library(fmt fmt PATHS ${CONAN_LIB_DIRS_FMT})
     if(fmt)
         target_link_libraries(fmt-conan INTERFACE ${fmt})
     else()
         message(FATAL_ERROR "Conan fmt binary not found")
     endif()
     ```

 - **Using fmt-conan in my project**:

    ``` cmake
    add_library(myib SHARED mylib.cpp)
    target_link_libraries(mylib PUBLIC fmt-conan)
    ```

After a successful configuration (conan's fmt binary is found by CMake's `find_library()`), make stops when linking mylib as follows:

``` bash
$ $HOME/.conan/data/fmt/3.0.0/memsharded/testing/package/<package hash>/lib/libfmt.a(format.cc.o): Relocation R_X86_64_32S against '.rodata' can not be used when making a shared object: Recompile with -fPIC
```

**Comment by memsharded** [comment]
Thanks for noticing! There was a small bug in the fPIC flag, missing space: https://github.com/memsharded/conan-fmt/commit/36bf4d1ebf96b71cf34ec93b6d2ca0de0eb76ce3

I have just submitted a fix, and CI is generating the package binaries, should be ready in a while. Windows and Linux already are, OSX still building on CI. Please try when possible and tell me if fixed, thanks very much.
