### ISSUE TITLE
Upgrade to 4.0.0 and possibly 3.0.2 version

### ISSUE THREAD

**Issue by hestad** [memsharded/conan-fmt#6]
https://github.com/fmtlib/fmt/releases/tag/4.0.0

https://github.com/fmtlib/fmt/releases/tag/3.0.2

**Comment by agauniyal** [comment]
4.0.0 brought lots of changes, an upgrade would be helpful 😄

**Comment by agauniyal** [comment]
4.0.0 brought lots of changes, an upgrade would be helpful 😄

**Comment by agauniyal** [comment]
4.0.0 brought lots of changes, an upgrade would be helpful 😄

**Comment by memsharded** [comment]
There is an official fmt 4.0.0 package in conan-center: https://bintray.com/bincrafters/public-conan/fmt%3Abincrafters

Created and maintained by the bincrafters community. I will no longer maintain this package, but collaborate with them, so I suggest pinging them for the 3.0.2 is still necessary. 

Thanks very much!

**Comment by hestad** [comment]
Would be nice if that information also was in this readme :+1:

**Comment by memsharded** [comment]
Good idea, done!
